### ISSUE TITLE
[Feature] Add Image Thumbnail for image fields

### ISSUE THREAD

**Issue by SalahAdDin** [rkhleics/wagtailmodeladmin#35]
Hi man, first i want say you that this package i'ts wonderful, so util, so good.

So, i have a model with a wagtailimage field, and i see that in list view this field doesn't show a thumbnail, in his place shown a title of image.
![wagtail - affiliates - mozilla firefox_014](https://cloud.githubusercontent.com/assets/5034215/12336648/8ec96400-bad3-11e5-85a0-6a3b2e91516e.png)

And when i want edit this model these field doesn't show a thumbnail images, show a select box with a list of images.
![wagtail - editing affiliate - mozilla firefox_015](https://cloud.githubusercontent.com/assets/5034215/12336664/a91eb7ce-bad3-11e5-9710-4393bd6cb09d.png)

Did you think about put a thumbnails in list view and thumbnails for select images?
If now we can do this, how can i do this?

Thank you very much.

PD: Select box filtes need some styles for their arrows. :D

**Comment by ababic** [comment]
hi @SalahAdDin. It looks like you could do with adding a `panels` attribute to your Affiliate model, to give you some control over the create/edit interface. If you used an `wagtail.wagtailimages.edit_handlers.ImageChooserPanel` for your logo field, that would give you a nice image chooser widget in your form.

In regards to displaying a thumbnail in your listing page, that's definitely possible, but will need a little bit of work. Just like Django's `ModelAdmin` class, the `list_display` attribute supports custom methods as well as simple field names (https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display). I would suggest adding a method to your model that generates the HTML for a thumbnail, then adding the name of that method to `list_display` in place of the logo field name.

As explained in the examples on the above link, you'll need to use `format_html()` or `mark_safe()` on the methods output, so that HTML isn't escaped when rendering the list page.

**Comment by SalahAdDin** [comment]
Ah, haven't wagtail a image chooser? Sorlthumbnail have a mixin for display an image in image in list display.

**Comment by ababic** [comment]
I'm closing this, as it's more of a support request than an issue, and I don't think I can help much more than I have already.

**Comment by SalahAdDin** [comment]
Yes man, if you think please put this information in docs.

**Comment by SalahAdDin** [comment]
@ababic Man, i think that will be better add panels in wagtailadmin, i think that is absurd put the panels in a model that haven't to do with wagtail models, but, for now, we have do this: add the panels in normal mode for work very good with wagtail admin. And i have put all, because if only put one, other fields isn't render, and isn't easy override panel options.

**Comment by SalahAdDin** [comment]
And edit_handlers doesn't work with normal pages.
