### ISSUE TITLE
Any way to hook wagtail's TabbedInterface from wagtailmodeladmin?

### ISSUE THREAD

**Issue by rjacks** [rkhleics/wagtailmodeladmin#38]
Is there any way to hook into Wagtail's TabbedInterface for non-Page models?  If not, it might make a nice enhancement.

**Comment by ababic** [comment]
Hi @rjacks. I'm sure it would be possible somehow by extending the classes, views and templates provided, if you'd like to give it a go and share your results for others... but i'm holding off on adding any significant functionality for a while (and likely forever). `wagtailmodeladmin` is due to become part of wagtail soon (as a contrib app), and there are currently several ongoing efforts to refactor a lot of the back-end functionality throughout wagtail, to make it dryer and more class-based... which in turn, would probably make any solution I came up with temporary.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by jmz-b** [comment]
My solution, just in case anyone else is looking

```
from wagtail.wagtailadmin.edit_handlers import (
    ObjectList, extract_panel_definitions_from_model_class
)
from wagtailmodeladmin.views import CreateView, EditView


class UserDefinedEditHandlerMixin(object):
    def get_edit_handler_class(self):
        if hasattr(self.model, 'edit_handler'):
            # use the edit handler specified on the class
            edit_handler = self.model.edit_handler
        else:
            edit_handler = ObjectList(
                extract_panel_definitions_from_model_class(self.model)
            )

        return edit_handler.bind_to_model(self.model)


class CreateView(UserDefinedEditHandlerMixin, CreateView):
    pass


class EditView(UserDefinedEditHandlerMixin, EditView):
    pass
```

Then in your ModelAdmin class

```
create_view_class = CreateView
edit_view_class = EditView
```

and on your model something like

```
edit_handler = TabbedInterface([
    ObjectList(some_panels, heading='whatever'),
    ObjectList(other_panels, heading='something'),
])
```

In order to make it look nice I had to do this in the create.html template:

```
{% include "wagtailadmin/shared/header.html" with title=view.get_page_title subtitle=view.get_page_subtitle icon=view.header_icon merged=1 tabbed=1 %}
```

Unfortunately this means overwriting the whole template, or at least the {% content %} block

**Comment by SalahAdDin** [comment]
mmmmm, so, will be better that this package or wagtail change the admin!

**Comment by ababic** [comment]
As simple as it may seem, I can't go ahead and just add this, because wagtailmodeladmin is purported to work seamlessly with models registered with snippets. But, if users were to define tabbed panels on a snippet model, they wouldn't work with the snippet management part of wagtail CMS, and you'd end up with 2 different editing interfaces for the same thing, which I feel is just a little too hacky. 

Once part of wagtail itself, there'll be scope to integrate better with core wagtail stuff, and provide a more consistant experience. Supporting tabbed interfaces for non-page models is really something that needs to come from the wagtail side, as part of refactoring views to share common functionally.

I'm meeting with torchbox within the next few weeks to share some ideas about how wagtailmodeladmin might evolve and take more of a central role within wagtail, and these are the kind of things I'd like to happen alongside that to give developers more control. It's going to be quite an involved process to make sure things are done right though, which I'm sure you can appreciate.

**Comment by SalahAdDin** [comment]
:+1:
