### ISSUE TITLE
Override wagtailmodeladmin templates

### ISSUE THREAD

**Issue by Luperi** [rkhleics/wagtailmodeladmin#46]
I'm trying to add new actions button. I've created my template in `/demo/templates/wagtailmodeladmin/includes/result_row_value.html` but nothing seems to appen. Any ideas? Thank you

**Comment by SalahAdDin** [comment]
Well, i only know that for the 1.5 wagtail version this feature could be added, but, while now, it's a quite problem. 
Maybe take a see in the branch could help you.

**Comment by ababic** [comment]
It's the ButtonHelper class that controls which buttons to show, and for which users. You shouldn't need to override that template. Take a look again at the treebeard recipe. In helpers.py, where the custom helpers are defined, and in options.py to see how they are applied to the TreebeardModelAdmin class

**Comment by Luperi** [comment]
@SalahAdDin what feature of wagtail 1.5 are you talking about? Thanks.

**Comment by Luperi** [comment]
Ok @ababic but how can I use this in my own project? There isn't a real documentation about this. I've simply to add a new button near "modify" and "delete" like this.

![example](https://cloud.githubusercontent.com/assets/4625424/13808842/5ff01bc2-eb68-11e5-9fc9-1026bd8945b4.png)

Based on your documentation, I've worked correctly with wagtailmodeladmin, but I don't understand why you are now talking about TreebeardModelAdmin, that is not mentioned at all [here](https://github.com/rkhleics/wagtailmodeladmin/blob/master/README.rst).

**Comment by ababic** [comment]
I'm only one man @Luperi, and I have a full-time job, and a family. I haven't had time to write thorough documentation on some of the newer stuff, but I have tried to help you as best I can.

**Comment by Luperi** [comment]
I know @ababic and I thank you, I'm only a bit confused.

**Comment by ababic** [comment]
The treebeard recipe has it's own custom ButtonHelper and PermissionHelper classes to do stuff that isn't covered by the default modeladmin setup (which you can find here: https://github.com/rkhleics/wagtailmodeladmin/blob/master/wagtailmodeladmin/recipes/treebeard/helpers.py), so I figured that would be a good example for you to copy from.

If you want extra buttons, you should create a custom ButtonHelper class too (in your project), by extending `wagtailmodeladmin.helpers.ButtonHelper`, adding a new method to generate a dictionary describing your button, and override the `get_buttons_for_obj` method to add your button where you want it.

Then you set the `button_helper_class` attribute on your ModelAdmin class to your custom button helper class, and it should work.

**Comment by Luperi** [comment]
Yes it works! It is still something incomprehensible for me how ButtonHelper can manage this kind of buttons, but ok. You have been very kind, thank you very much.

**Comment by ababic** [comment]
The button logic used to live in the IndexView, but I often found myself wanting to customise it, and it didn't seem logical to me to have to override the IndexView to do that every time, just to add a new view. I also thought there could well be cases where I might want reuse the logic, so having it separated out made a lot of sense.

I first considered adding it to one of the more abstract views, but they already felt a bit overcomplicated. I also considered adding it to the ModelAdmin class itself, but I made a conscious decision to try to keep that as light as possible, because I wanted ModelAdmin to act as a 'central hub', where all the various customisable  bits plug into. Kind of like a PC, where you can upgrade and plug in new cards as and when you need to. 

And so, the ButtonHelper was born!

**Comment by Luperi** [comment]
That's awesome! Excuse me if I seemed rude, I was only trying to understand more about these stuff. I'm new to wagtail and, in general, to django. I'm trying to study and understand as I can.. Contributing to wagtail too. Your help has been very precious... So, thank you very much and good job! :)

**Comment by ababic** [comment]
Thanks. I wish you all the best with it. I think you caught wagtail at a good time. It's still in its early days, but they're taking on board a lot of feedback from developers and have a good idea about where they want to go with it. We're all still learning :)

**Comment by Luperi** [comment]
Will be ButtonHelper available also when wagtailmodeladmin will be integrated with wagtail 1.5 version? When I will update to that version, I will not need to change my code, right? Thanks

**Comment by ababic** [comment]
There are some minor differences between this version and the one that's going into wagtail, so that is something you'll need to consider before updating a project to use wagtail 1.5. Nobody is forcing anybody to upgrade to wagtail 1.5 when it is released, though. You can still happily run a site on wagtail 1.4 or earlier and carry on using this package.

**Comment by Luperi** [comment]
Yes, obviously. But in wagtail 1.5 will be probably integrated also my pending pull requests.. so upgrading could be good :smiley:

**Comment by ababic** [comment]
Things are about 98% similar currently, so upgrading should be as simple as changing the import locations for modeladmin stuff.

But... that's just based on the pull request in it's current state... I can't guarantee things won't change between now and the 1.5 launch.
