### ISSUE TITLE
exclude not working

### ISSUE THREAD

**Issue by Luperi** [rkhleics/wagtailmodeladmin#47]
I'm trying to display only certain fields while editing a model. I've tried with exclude but it does not work. This isn't the right way? The model in question extends django User model.

```
class VendorModelAdmin(ModelAdmin):
    model = Vendor
    menu_label = 'Vendors'
    menu_icon = 'user'
    add_to_settings_menu = False
    list_display = ('username', 'first_name', 'last_name', )
    search_fields = ('first_name', 'last_name', )
    exclude = ('first_name', ) 
```

also tried with:

```
class VendorModelAdmin(ModelAdmin):
    model = Vendor
    menu_label = 'Vendors'
    menu_icon = 'user'
    add_to_settings_menu = False
    list_display = ('username', 'first_name', 'last_name', )
    list_filter = ('fk_vendor', )
    search_fields = ('first_name', 'last_name', )

    def get_form(self, request, obj=None, **kwargs):
        self.exclude = []
        self.exclude.append('first_name')
        return super(VendorModelAdmin, self).get_form(request, obj, **kwargs)
```

**Comment by ababic** [comment]
The major difference between this ModelAdmin and Django's one, is this one
doesn't control anything on the create/edit pages. The fields that show in
those forms are still controlled by the edit panels defined on model
classes (although, hopefully this is something that will be controllable
via similar fields in future!)

On 17 March 2016 at 17:28, Luca Perico <notifications@github.com> wrote:

> I'm trying to display only certain fields while editing a model. I've
> tried with exclude but it does not work. This isn't the right way? The
> model in question extends django User model.
>
> class VendorModelAdmin(ModelAdmin):
>     model = Vendor
>     menu_label = 'Vendors'
>     menu_icon = 'user'
>     add_to_settings_menu = False
>     list_display = ('username', 'first_name', 'last_name', )
>     search_fields = ('first_name', 'last_name', )
>     exclude = ('first_name', )
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rkhleics/wagtailmodeladmin/issues/47>
>



-- 
Andy Babic
Web Developer

Rock Kitchen Harris Ltd, 32 Pocklingtons Walk, Leicester LE1 6BU
0116 233 7500 | www.rkh.co.uk | Reg. No. 1589727

**Comment by Luperi** [comment]
So, the only way seems to be to modify wagtail code? Because I don't know how to specify which form use when edit page of model is rendered.

**Comment by ababic** [comment]
No, you don't need to change wagtail code.

Remember the links to the wagtail docs I sent you earlier in the week,
regarding panels? You need to just create a 'panels' attribute on the
model, to tell wagtail what fields to display for that model.

ModelAdmin reads the 'panels' attribute the same way as Wagtail's snippet
management views do. If there's no 'panels' attribute, I think it just
tries to show every field on the model.

**Comment by Luperi** [comment]
Yes, I know. But is more complex in this case.

`from wagtail.wagtailusers.models import UserProfile` extends django User model. In wagtail has been defined a custom form that shows certain fields. If I want to extend UserProfile with my own fields and call it "Vendor" and edit all with a form similar to UserProfile one, how can I do?

(excuse me for my bad english, I'm italian)

**Comment by ababic** [comment]
I don't think wagtailmodeladmin can help you with overriding core wagtail
things. All it does is hook in extra menu items, URLs and views for
additional models. It doesn't override any core wagtail functionality.

You might have better luck raising your issue in the wagtail support group:

https://groups.google.com/forum/?nomobile=true#!forum/wagtail

Yes, I know. But is more complex in this case.

from wagtail.wagtailusers.models import UserProfile extends django User
model. In wagtail has been defined a custom form that shows certain fields.
If I want to extend UserProfile with my own fields and call it "Vendor" and
edit all with a form similar to UserProfile one, how can I do?

(excuse me for my bad english, I'm italian)

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/rkhleics/wagtailmodeladmin/issues/47#issuecomment-198105273>
