### ISSUE TITLE
hooks for queryset filtering

### ISSUE THREAD

**Issue by Luperi** [rkhleics/wagtailmodeladmin#48]
Hi, in wagtail 1.4 have been introduced a new hooks [construct_explorer_page_queryset](http://docs.wagtail.io/en/v1.4.1/reference/hooks.html#page-explorer) that allows you to filter page queryset. Could we implement something similar in `wagtailmodeladmin` to filter a model? For example, if I have a "Order" model and I want to show only orders inserted by current user. 

I think in `wagtailmodeladmin.views.IndexView` we should do something like `wagtailadmin.views.index` where they use:

```
# allow hooks to modify the queryset
    for hook in hooks.get_hooks('construct_explorer_page_queryset'):
        pages = hook(parent_page, pages, request)

```

**Comment by ababic** [comment]
Hi @Luperi. Wagtail hooks exist to give control over what is otherwise fixed functionality. Hooks aren't needed for wagtailmodeladmin, because the whole view / ModelAdmin class is under your control.

The best way to achieve this currently, is to override the `get_queryset` method on your ModelAdmin class:

https://github.com/rkhleics/wagtailmodeladmin/blob/master/wagtailmodeladmin/options.py#L236. 

It takes the `request` as an argument, so you can get the currently logged-in user from that, and filter accordingly. That method returns the 'base' queryset for the index view.... any dynamic filters / ordering will then be applied to that.

**Comment by Luperi** [comment]
Yes, it works. Thank you!!
