### ISSUE TITLE
static css files not found

### ISSUE THREAD

**Issue by ronniestevens** [rkhleics/wagtailmodeladmin#52]
I added wagtail.contrib.modeladmin to my base.py, and run 'manage.py collectstatic', but the static files are in 'static/wagtailmodeladmin/css', while the app searches these in 'static/modeladmin/css'. Creating the latter manually resolves the issue.
Wagtail 1.5.2.

**Comment by ababic** [comment]
Hi @ronniestevens. Sorry, I'm slightly confused here. I think this issue is with `wagtail.contrib.modeladmin` package, in which case the issue needs raising on the [Wagtail project issue tracker](https://github.com/torchbox/wagtail/issues), rather than here... unless you're installing `wagtailmodeladmin` as a separate package, still?

**Comment by ronniestevens** [comment]
you are quite right, my wrong :-)
