### ISSUE TITLE
Showing ManyToMany relationship with through model.

### ISSUE THREAD

**Issue by Eraldo** [rkhleics/wagtailmodeladmin#53]
Currently I have a many-to-many relationship on one of my models and it does show the target model as a multi-selectPanel however it does not show my through model fields.

Sample code snippet:
```python
    portals = models.ManyToManyField(
        to='Portal',
        verbose_name=_('portals'),
        through='PortalLink',
    )
```

I get a list of portals to select (without the fields of the PortalLink model)

Plus: I get the following error when trying to save without the relationship..
`Cannot set values on a ManyToManyField which specifies an intermediary model. Use inventory.PortalLink's Manager instead.`

Any ideas here?
I'd be glad for feedback/guidance.

Best,
Eraldo

**Comment by ababic** [comment]
Hi @Eraldo,

This is more a limitation of Wagtail, than of wagtailmodeladmin. Any field/form rendering you see in wagtailmodeladmin is handled via Wagtail's built-in edit_handler components, and Wagtail doesn't have support for ManyToManyField.

BTW, If you're using wagtail version 1.5 or above, you should use the contrib app that is packaged with wagtail, instead of this outdated version of the app (which is no longer supported). Take a look at:

http://docs.wagtail.io/en/latest/reference/contrib/modeladmin.html
